name: Deploy
run-name: Deploy to lambda
on:
  push:
  workflow_dispatch:
jobs:
  Package-Zip:
    runs-on: ubuntu-latest # Packaging is needed to be executed on Linux to make psycopg2 work on Labmda environment. See https://stackoverflow.com/a/46366104
    steps:
      - run: echo "Packaging..."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: mkdir -p dist/lambda-package
      - run: pip install poetry
      - run: poetry install --only main --sync
      - run: cp -r .venv/lib/python*/site-packages/* dist/lambda-package/
      - run: cp -r src/app/pkg/* dist/lambda-package/
      - run: cd dist/lambda-package
      - run: zip -r ../lambda.zip .
      - name: Upload the zip file
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: ../lambda.zip
      - run: echo "🍏 This job's status is ${{ job.status }}."
  Update-Lambda:
    needs: Package-Zip
    runs-on: ubuntu-latest
    steps:
      - run: echo "Updating lambda..."
      - name: Download the zip file from Package-Zip
        uses: actions/download-artifact@v4
        with:
          name: lambda-package
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION
      - run: aws s3 cp lambda.zip s3://$AWS_S3_BUCKET_NAME/$AWS_S3_OBJECT_NAME
      - run: aws lambda update-function-code --function-name $AWS_LAMBDA_FUNCTION_NAME --zip-file --s3-bucket $AWS_S3_BUCKET_NAME --s3-key $AWS_S3_OBJECT_NAME
      - run: echo "🍏 This job's status is ${{ job.status }}."
